- generic [active] [ref=e1]:
  - main [ref=e2]:
    - generic [ref=e3]:
      - img "Glean Logo" [ref=e5]
      - generic [ref=e6]:
        - link "Back to jobs" [ref=e7] [cursor=pointer]:
          - /url: https://job-boards.greenhouse.io/gleanwork
          - img [ref=e8]
          - text: Back to jobs
        - generic [ref=e11]:
          - generic [ref=e12]:
            - heading "Founding Forward Deployed Engineer" [level=1] [ref=e13]
            - generic [ref=e14]:
              - img [ref=e15]
              - generic [ref=e17]: Remote - US
          - button "Apply" [ref=e18] [cursor=pointer]
        - generic [ref=e19]:
          - generic [ref=e20]:
            - strong [ref=e23]: "About Glean:"
            - generic [ref=e25]: Glean is the Work AI platform that helps everyone work smarter with AI. What began as the industry’s most advanced enterprise search has evolved into a full-scale Work AI ecosystem, powering intelligent Search, an AI Assistant, and scalable AI agents on one secure, open platform. With over 100 enterprise SaaS connectors, flexible LLM choice, and robust APIs, Glean gives organizations the infrastructure to govern, scale, and customize AI across their entire business - without vendor lock-in or costly implementation cycles.
            - generic [ref=e27]: "At its core, Glean is redefining how enterprises find, use, and act on knowledge. Its Enterprise Graph and Personal Knowledge Graph map the relationships between people, content, and activity, delivering deeply personalized, context-aware responses for every employee. This foundation powers Glean’s agentic capabilities - AI agents that automate real work across teams by accessing the industry’s broadest range of data: enterprise and world, structured and unstructured, historical and real-time. The result: measurable business impact through faster onboarding, hours of productivity gained each week, and smarter, safer decisions at every level."
            - generic [ref=e29]: Recognized by Fast Company as one of the World’s Most Innovative Companies (Top 10, 2025), by CNBC’s Disruptor 50, Bloomberg’s AI Startups to Watch (2026), Forbes AI 50, and Gartner’s Tech Innovators in Agentic AI, Glean continues to accelerate its global impact. With customers across 50+ industries and 1,000+ employees in more than 25 countries, we’re helping the world’s largest organizations make every employee AI-fluent, and turning the superintelligent enterprise from concept into reality.
            - generic [ref=e31]: If you’re excited to shape how the world works, you’ll help build systems used daily across Microsoft Teams, Zoom, ServiceNow, Zendesk, GitHub, and many more - deeply embedded where people get things done. You’ll ship agentic capabilities on an open, extensible stack, with the craft and care required for enterprise trust, as we bring Work AI to every employee, in every company.
          - generic [ref=e34]:
            - strong [ref=e37]: "About the Role:"
            - generic [ref=e39]: You'll join as a founding member of Glean's forward deployed team and operate with the autonomy and accountability of a founder. Your job is to discover and build Glean's next generation of product surfaces, working in a pod with Forward Deployed PMs directly with the C-suite of the world's most influential companies and with Glean's own engineering and product teams.
            - generic [ref=e41]: Glean is a fully horizontal AI platform - and that scope is what makes this role unique. You won't be configuring existing products or optimizing within defined constraints. You'll identify the biggest unsolved business problems at our most strategic customers, build entirely new products to solve them, and in doing so shape what Glean becomes. The best of what you build ships to every Glean customer in the world. You get founder-level ownership with Glean's resources, relationships, and scale behind you.
            - strong [ref=e45]: "You will:"
            - list [ref=e47]:
              - listitem [ref=e48]:
                - generic [ref=e49]:
                  - strong [ref=e50]: "Discover and build Glean's next product surfaces:"
                  - text: Your primary job is 0-to-1 product creation. Nothing about what you're building is predefined - you'll work with your FDPM to identify where Glean's platform can be extended to solve problems no product currently solves, then design and ship it. What you build becomes what Glean ships.
              - listitem [ref=e51]:
                - generic [ref=e52]:
                  - strong [ref=e53]: "Lead deep opportunity discovery:"
                  - text: Before you write a line of code, you go deep on the business. What's structurally broken? Where is the biggest concentration of unsolved value? What's actually buildable, and what's the fastest path to something real that can be tested and learned from? You'll form strong hypotheses alongside your FDPM and pressure-test them directly with the people who have to live with the outcome.
              - listitem [ref=e54]:
                - generic [ref=e55]:
                  - strong [ref=e56]: "Be a technical partner to the C-suite:"
                  - text: You'll earn trust at the highest levels of your customer organizations - not just with technical teams, but with the executives who are accountable for outcomes. You can explain what you're building, why it will work, and what the risks are to anyone in the room.
              - listitem [ref=e57]:
                - generic [ref=e58]:
                  - strong [ref=e59]: Scale what works
                  - text: Once something works, you'll make it repeatable - working closely with the core R&D team to ensure the product is scalable
              - listitem [ref=e60]:
                - generic [ref=e61]:
                  - strong [ref=e62]: "Stay at the frontier with Glean's R&D team:"
                  - text: You'll work closely with Glean's core engineering and product teams, staying ahead of what's possible on the platform and actively shaping how its capabilities evolve. What you encounter in the field directly informs what gets built next.
            - strong [ref=e65]: "About you:"
            - list [ref=e67]:
              - listitem [ref=e68]: You think like a founder. When you walk into a customer, you're curious about the business, digging into what's broken, and figuring out what to build that doesn't yet exist. You're scrappy and resourceful, you move fast enough to learn, and you're as comfortable in a strategic discussion with a CEO as you are deep in a codebase. You've shipped actual products that real people use, that drove real outcomes - and you want to do it at a higher level of ambition.
              - listitem [ref=e69]:
                - generic [ref=e70]:
                  - strong [ref=e71]: "0-to-1 build track record:"
                  - text: You've built production software from scratch in ambiguous environments. You can point to something that didn't exist before you showed up and is now used by real people at scale.
              - listitem [ref=e72]:
                - generic [ref=e73]:
                  - strong [ref=e74]: "Production AI experience:"
                  - text: You've shipped AI-powered solutions in the real world - prompt engineering, agent development, evaluation frameworks, deployment at scale. Not just prototypes.
              - listitem [ref=e75]:
                - generic [ref=e76]:
                  - strong [ref=e77]: "Full-stack technical depth:"
                  - text: Strong programming skills across the stack with a deep understanding of and experience with how enterprise systems actually work.
              - listitem [ref=e78]:
                - generic [ref=e79]:
                  - strong [ref=e80]: "Business acumen:"
                  - text: You can walk into a customer, identify where the real problems are, and connect that diagnosis to a product hypothesis - without being handed a brief.
              - listitem [ref=e81]:
                - generic [ref=e82]:
                  - strong [ref=e83]: "Customer instinct:"
                  - text: You build trust quickly at every level of an organization, communicate with clarity, and know how to tailor your depth to the room.
              - listitem [ref=e84]:
                - generic [ref=e85]:
                  - strong [ref=e86]: "Builder's judgment:"
                  - text: You know what's actually buildable, how long it will take, and when to simplify scope to get something real into production faster. You spot problems early and solve them independently.
              - listitem [ref=e87]:
                - generic [ref=e88]:
                  - strong [ref=e89]: "Curiosity and scrappiness:"
                  - text: You're driven to understand problems deeply before solving them, and resourceful enough to find a path forward when none is obvious.
              - listitem [ref=e90]:
                - generic [ref=e91]:
                  - strong [ref=e92]: "Experience:"
                  - text: 4+ years in technical roles with a track record of shipping production software. Former technical founders are strongly encouraged to apply.
              - listitem [ref=e93]:
                - generic [ref=e94]:
                  - strong [ref=e95]: "Willingness to travel:"
                  - text: This role requires 25–50% travel.
              - listitem [ref=e96]:
                - strong [ref=e98]: "Nice to Have:"
                - list [ref=e99]:
                  - listitem [ref=e100]: Experience as a founder, at a top-tier technology company, or in a forward deployed engineering role.
                  - listitem [ref=e101]: A technical degree in CS, engineering, math, or a related field.
                  - listitem [ref=e102]: Deep familiarity with LLMs, retrieval systems, and evaluation frameworks.
                  - listitem [ref=e103]: Experience driving technology adoption inside large enterprises.
            - strong [ref=e106]: "Location:"
            - list [ref=e108]:
              - listitem [ref=e109]: This role is remote
              - listitem [ref=e110]: This role requires 25-50% travel
            - strong [ref=e113]: "Compensation & Benefits:"
            - generic [ref=e115]: "The standard range for this position is $160,000-$270,000 annually. Compensation offered will be determined by factors such as location, level, job-related knowledge, skills, and experience. Certain roles may be eligible for variable compensation, equity, and benefits. Special Note: This range encompasses varying levels of the role, you will be assessed for your level during the interview process."
            - generic [ref=e117]: We offer a comprehensive benefits package including competitive compensation, Medical, Vision, and Dental coverage, generous time-off policy, and the opportunity to contribute to your 401k plan to support your long-term goals. When you join, you'll receive a home office improvement stipend, as well as an annual education and wellness stipends to support your growth and wellbeing. We foster a vibrant company culture through regular events, and provide healthy lunches daily to keep you fueled and focused.
            - generic [ref=e119]: We are a diverse bunch of people and we want to continue to attract and retain a diverse range of people into our organization. We're committed to an inclusive and diverse company. We do not discriminate based on gender, ethnicity, sexual orientation, religion, civil or family status, age, disability, or race.
            - generic [ref=e121]: "#LI-REMOTE"
          - generic [ref=e122]:
            - strong [ref=e126]: "AI-First Mindset at Glean:"
            - generic [ref=e129]:
              - text: At Glean, AI fluency is core to how we work and we're committed to ensuring every new hire feels confident integrating AI into their everyday work.
              - strong [ref=e130]: As part of the interview process, you'll complete a brief AI-focused exercise or discussion so we can understand how you think about, design, and use AI to drive impact in your role.
              - text: Feel free to reference any tools, platforms, or workflows you use today — prior Glean experience isn't required.
            - strong [ref=e134]: "Global Data Privacy Notice for Job Candidates and Applicants:"
            - generic [ref=e137]:
              - text: Depending on your location, the General Data Protection Regulation (GDPR), California Consumer Privacy Act (CCPA), or other privacy laws may regulate the way we manage the data of job applicants. Our full notice outlining how data will be processed as part of the application procedure for applicable locations is available in our
              - link "Privacy Policy" [ref=e138] [cursor=pointer]:
                - /url: https://www.glean.com/privacy
                - strong [ref=e139]: Privacy Policy
              - text: . By submitting your application, you are agreeing to our use and processing of your data as required. US applicants and their applications are subject to arbitration of disputes as outlined in our
              - link "Applicant Arbitration Agreement" [ref=e140] [cursor=pointer]:
                - /url: https://www.glean.com/arbitrationagreement
                - strong [ref=e141]: Applicant Arbitration Agreement
              - text: .
            - generic [ref=e143]:
              - text: By clicking “Submit Application,” I confirm that I have read the Global Data Privacy Notice and the
              - link "Applicant Arbitration Agreement" [ref=e144] [cursor=pointer]:
                - /url: https://www.glean.com/arbitrationagreement
                - strong [ref=e145]: Applicant Arbitration Agreement
              - text: ", and I agree to the terms."
        - generic [ref=e146]:
          - img [ref=e147]
          - generic [ref=e149]:
            - paragraph [ref=e150]: Create a Job Alert
            - paragraph [ref=e151]: Interested in building your career at Glean? Get future opportunities sent straight to your email.
            - link "Create alert" [ref=e152] [cursor=pointer]:
              - /url: https://my.greenhouse.io/users/sign_in?job_board=gleanwork&source=job_alert_post
      - separator [ref=e153]
      - generic [ref=e154]:
        - generic [ref=e155]:
          - generic [ref=e156]:
            - heading "Apply for this job" [level=2] [ref=e158]
            - generic [ref=e159]:
              - paragraph [ref=e161]: "*"
              - paragraph [ref=e162]: indicates a required field
          - button "Autofill with MyGreenhouse" [ref=e165] [cursor=pointer]
        - generic [ref=e166]:
          - generic [ref=e167]:
            - generic [ref=e170]:
              - generic [ref=e171]: First Name*
              - textbox "First Name" [ref=e172]
            - generic [ref=e175]:
              - generic [ref=e176]: Last Name*
              - textbox "Last Name" [ref=e177]
            - generic [ref=e180]:
              - generic [ref=e181]: Email*
              - textbox "Email" [ref=e182]
            - group "Phone" [ref=e184]:
              - generic [ref=e185]: Phone
              - generic [ref=e188]:
                - generic [ref=e189]: Country
                - generic [ref=e190]:
                  - log [ref=e192]
                  - generic [ref=e194]:
                    - combobox "Country" [ref=e197]
                    - button "Toggle flyout" [ref=e199] [cursor=pointer]:
                      - img [ref=e200]
              - generic [ref=e204]:
                - generic [ref=e205]: Phone
                - textbox "Phone" [ref=e207]
            - group "Resume/CV" [ref=e209]:
              - generic [ref=e210]: Resume/CV
              - generic [ref=e212]:
                - generic [ref=e214]:
                  - button "Attach" [ref=e215] [cursor=pointer]
                  - generic [ref=e216]: Attach
                  - button "Attach" [ref=e217]
                - button "Dropbox" [ref=e219] [cursor=pointer]
                - button "Google Drive" [ref=e221] [cursor=pointer]
                - generic [ref=e223]:
                  - button "Enter manually" [ref=e224] [cursor=pointer]
                  - generic [ref=e225]: Enter manually
                - paragraph [ref=e226]: "Accepted file types: pdf, doc, docx, txt, rtf"
            - group "Cover Letter" [ref=e228]:
              - generic [ref=e229]: Cover Letter
              - generic [ref=e231]:
                - generic [ref=e233]:
                  - button "Attach" [ref=e234] [cursor=pointer]
                  - generic [ref=e235]: Attach
                  - button "Attach" [ref=e236]
                - button "Dropbox" [ref=e238] [cursor=pointer]
                - button "Google Drive" [ref=e240] [cursor=pointer]
                - generic [ref=e242]:
                  - button "Enter manually" [ref=e243] [cursor=pointer]
                  - generic [ref=e244]: Enter manually
                - paragraph [ref=e245]: "Accepted file types: pdf, doc, docx, txt, rtf"
          - generic [ref=e246]:
            - separator [ref=e247]
            - generic [ref=e250]:
              - generic [ref=e251]: LinkedIn Profile*
              - textbox "LinkedIn Profile" [ref=e252]
            - generic [ref=e255]:
              - generic [ref=e256]: Website
              - textbox "Website" [ref=e257]
            - generic [ref=e260]:
              - generic [ref=e261]: Do you know anyone currently at Glean?*
              - textbox "Do you know anyone currently at Glean?" [ref=e262]
            - generic [ref=e265]:
              - generic [ref=e266]: How did you hear about Glean?*
              - generic [ref=e267]:
                - log [ref=e269]
                - generic [ref=e271]:
                  - generic [ref=e272]:
                    - generic [ref=e273]: Select...
                    - combobox "How did you hear about Glean?" [ref=e275]
                  - button "Toggle flyout" [ref=e277] [cursor=pointer]:
                    - img [ref=e278]
                - textbox
            - generic [ref=e282]:
              - generic [ref=e283]: What are your compensation expectations? ("negotiable" "market" and similar responses will not be reviewed)*
              - textbox "What are your compensation expectations? (\"negotiable\" \"market\" and similar responses will not be reviewed)" [ref=e284]
            - generic [ref=e287]:
              - generic [ref=e288]: Have you built AI agents? If so, please elaborate. *
              - generic [ref=e289]:
                - log [ref=e291]
                - generic [ref=e293]:
                  - generic [ref=e294]:
                    - generic [ref=e295]: Select...
                    - combobox "Have you built AI agents? If so, please elaborate." [ref=e297]
                  - button "Toggle flyout" [ref=e299] [cursor=pointer]:
                    - img [ref=e300]
                - textbox
            - generic [ref=e304]:
              - generic [ref=e305]: Please input the total years of experience you have that are relevant for this role.*
              - textbox "Please input the total years of experience you have that are relevant for this role." [ref=e306]
            - generic [ref=e309]:
              - generic [ref=e310]: What AI tools are you currently using today and how are you using them?*
              - textbox "What AI tools are you currently using today and how are you using them?" [ref=e311]
          - generic [ref=e312]:
            - separator [ref=e313]
            - generic [ref=e314]:
              - heading "Voluntary Self-Identification" [level=2] [ref=e315]
              - paragraph [ref=e316]: For government reporting purposes, we ask candidates to respond to the below self-identification survey. Completion of the form is entirely voluntary. Whatever your decision, it will not be considered in the hiring process or thereafter. Any information that you do provide will be recorded and maintained in a confidential file.
              - paragraph [ref=e317]: As set forth in Glean’s Equal Employment Opportunity policy, we do not discriminate on the basis of any protected group status under any applicable law.
            - generic [ref=e320]:
              - generic [ref=e321]: Gender
              - generic [ref=e322]:
                - log [ref=e324]
                - generic [ref=e326]:
                  - generic [ref=e327]:
                    - generic [ref=e328]: Select...
                    - combobox "Gender" [ref=e330]
                  - button "Toggle flyout" [ref=e332] [cursor=pointer]:
                    - img [ref=e333]
            - generic [ref=e335]:
              - generic [ref=e337]:
                - generic [ref=e338]: Are you Hispanic/Latino?
                - generic [ref=e339]:
                  - log [ref=e341]
                  - generic [ref=e343]:
                    - generic [ref=e344]:
                      - generic [ref=e345]: Select...
                      - combobox "Are you Hispanic/Latino?" [ref=e347]
                    - button "Toggle flyout" [ref=e349] [cursor=pointer]:
                      - img [ref=e350]
              - link "Race & Ethnicity Definitions" [ref=e352] [cursor=pointer]:
                - /url: https://job-boards.cdn.greenhouse.io/docs/2023/RaceEthnicityDefinitions.pdf
            - generic [ref=e353]:
              - paragraph [ref=e354]: "If you believe you belong to any of the categories of protected veterans listed below, please indicate by making the appropriate selection. As a government contractor subject to the Vietnam Era Veterans Readjustment Assistance Act (VEVRAA), we request this information in order to measure the effectiveness of the outreach and positive recruitment efforts we undertake pursuant to VEVRAA. Classification of protected categories is as follows:"
              - paragraph [ref=e355]: "A \"disabled veteran\" is one of the following: a veteran of the U.S. military, ground, naval or air service who is entitled to compensation (or who but for the receipt of military retired pay would be entitled to compensation) under laws administered by the Secretary of Veterans Affairs; or a person who was discharged or released from active duty because of a service-connected disability."
              - paragraph [ref=e356]: A "recently separated veteran" means any veteran during the three-year period beginning on the date of such veteran's discharge or release from active duty in the U.S. military, ground, naval, or air service.
              - paragraph [ref=e357]: An "active duty wartime or campaign badge veteran" means a veteran who served on active duty in the U.S. military, ground, naval or air service during a war, or in a campaign or expedition for which a campaign badge has been authorized under the laws administered by the Department of Defense.
              - paragraph [ref=e358]: An "Armed forces service medal veteran" means a veteran who, while serving on active duty in the U.S. military, ground, naval or air service, participated in a United States military operation for which an Armed Forces service medal was awarded pursuant to Executive Order 12985.
            - generic [ref=e361]:
              - generic [ref=e362]: Veteran Status
              - generic [ref=e363]:
                - log [ref=e365]
                - generic [ref=e367]:
                  - generic [ref=e368]:
                    - generic [ref=e369]: Select...
                    - combobox "Veteran Status" [ref=e371]
                  - button "Toggle flyout" [ref=e373] [cursor=pointer]:
                    - img [ref=e374]
            - separator [ref=e376]
            - generic [ref=e377]:
              - heading "Voluntary Self-Identification of Disability" [level=2] [ref=e378]
              - generic [ref=e379]:
                - generic [ref=e380]:
                  - generic [ref=e381]: Form CC-305
                  - generic [ref=e382]: Page 1 of 1
                - generic [ref=e383]:
                  - generic [ref=e384]: OMB Control Number 1250-0005
                  - generic [ref=e385]: Expires 04/30/2026
              - strong [ref=e386]: Why are you being asked to complete this form?
              - paragraph [ref=e387]: We are a federal contractor or subcontractor. The law requires us to provide equal employment opportunity to qualified people with disabilities. We have a goal of having at least 7% of our workers as people with disabilities. The law says we must measure our progress towards this goal. To do this, we must ask applicants and employees if they have a disability or have ever had one. People can become disabled, so we need to ask this question at least every five years.
              - paragraph [ref=e388]:
                - text: Completing this form is voluntary, and we hope that you will choose to do so. Your answer is confidential. No one who makes hiring decisions will see it. Your decision to complete the form and your answer will not harm you in any way. If you want to learn more about the law or this form, visit the U.S. Department of Labor’s Office of Federal Contract Compliance Programs (OFCCP) website at
                - link "www.dol.gov/ofccp" [ref=e389] [cursor=pointer]:
                  - /url: https://www.dol.gov/ofccp
                - text: .
              - strong [ref=e390]: How do you know if you have a disability?
              - paragraph [ref=e391]:
                - text: A disability is a condition that substantially limits one or more of your “major life activities.” If you have or have ever had such a condition, you are a person with a disability.
                - strong [ref=e392]: "Disabilities include, but are not limited to:"
              - list [ref=e393]:
                - listitem [ref=e394]: Alcohol or other substance use disorder (not currently using drugs illegally)
                - listitem [ref=e395]: Autoimmune disorder, for example, lupus, fibromyalgia, rheumatoid arthritis, HIV/AIDS
                - listitem [ref=e396]: Blind or low vision
                - listitem [ref=e397]: Cancer (past or present)
                - listitem [ref=e398]: Cardiovascular or heart disease
                - listitem [ref=e399]: Celiac disease
                - listitem [ref=e400]: Cerebral palsy
                - listitem [ref=e401]: Deaf or serious difficulty hearing
                - listitem [ref=e402]: Diabetes
                - listitem [ref=e403]: Disfigurement, for example, disfigurement caused by burns, wounds, accidents, or congenital disorders
                - listitem [ref=e404]: Epilepsy or other seizure disorder
                - listitem [ref=e405]: Gastrointestinal disorders, for example, Crohn's Disease, irritable bowel syndrome
                - listitem [ref=e406]: Intellectual or developmental disability
                - listitem [ref=e407]: Mental health conditions, for example, depression, bipolar disorder, anxiety disorder, schizophrenia, PTSD
                - listitem [ref=e408]: Missing limbs or partially missing limbs
                - listitem [ref=e409]: Mobility impairment, benefiting from the use of a wheelchair, scooter, walker, leg brace(s) and/or other supports
                - listitem [ref=e410]: Nervous system condition, for example, migraine headaches, Parkinson’s disease, multiple sclerosis (MS)
                - listitem [ref=e411]: Neurodivergence, for example, attention-deficit/hyperactivity disorder (ADHD), autism spectrum disorder, dyslexia, dyspraxia, other learning disabilities
                - listitem [ref=e412]: Partial or complete paralysis (any cause)
                - listitem [ref=e413]: Pulmonary or respiratory conditions, for example, tuberculosis, asthma, emphysema
                - listitem [ref=e414]: Short stature (dwarfism)
                - listitem [ref=e415]: Traumatic brain injury
            - generic [ref=e418]:
              - generic [ref=e419]: Disability Status
              - generic [ref=e420]:
                - log [ref=e422]
                - generic [ref=e424]:
                  - generic [ref=e425]:
                    - generic [ref=e426]: Select...
                    - combobox "Disability Status" [ref=e428]
                  - button "Toggle flyout" [ref=e430] [cursor=pointer]:
                    - img [ref=e431]
            - paragraph [ref=e434]: "PUBLIC BURDEN STATEMENT: According to the Paperwork Reduction Act of 1995 no persons are required to respond to a collection of information unless such collection displays a valid OMB control number. This survey should take about 5 minutes to complete."
          - button "Submit application" [ref=e436] [cursor=pointer]
  - contentinfo [ref=e437]:
    - generic [ref=e438]:
      - paragraph [ref=e439]: Powered by
      - link "Greenhouse logo" [ref=e440] [cursor=pointer]:
        - /url: https://www.greenhouse.com
        - img "Greenhouse logo" [ref=e441]
  - iframe [ref=e455]:
    - generic [ref=f16e6]:
      - text: protected by
      - strong [ref=f16e7]: reCAPTCHA