#!/usr/bin/env bats
# Orchestration tests for scripts/hermes/tick.sh.
# Strategy: prepend scripts/hermes/tests/stubs/ to PATH so all external
# commands (hermes, gh, curl, git, jq) are replaced with shell scripts
# that write deterministic output and log calls to $STUB_LOG.

setup() {
  export TEST_TMPDIR="$(mktemp -d 2>/dev/null || mktemp -d -t hermes-tick)"
  export STUB_LOG="$TEST_TMPDIR/stub-calls.log"
  export CHITIN_SINK_ROOT="$TEST_TMPDIR/chitin-sink"
  export HERMES_TICK_TS="20260422T000000Z"         # deterministic tick dir name
  export HERMES_TICK_DATE="2026-04-22"
  # Isolate tick-level state that now has env overrides (lock file,
  # worktree base, repo root). Keeps tests from touching the real /tmp
  # lock or ~/workspace. The repo root is where stage 2 runs
  # `git apply --check` — bare dir is enough since `git` is stubbed.
  export HERMES_TICK_LOCK_FILE="$TEST_TMPDIR/hermes-tick.lock"
  export HERMES_TICK_WORKTREE_BASE="$TEST_TMPDIR/worktrees"
  export HERMES_TICK_REPO_ROOT="$TEST_TMPDIR/repo"
  mkdir -p "$CHITIN_SINK_ROOT/ticks" "$HERMES_TICK_WORKTREE_BASE" "$HERMES_TICK_REPO_ROOT"
  : > "$STUB_LOG"

  STUBS="$BATS_TEST_DIRNAME/stubs"
  export PATH="$STUBS:$PATH"

  # Defaults; individual tests can override by exporting STUB_* before run
  export STUB_HERMES_PLAN_OUTPUT='{"action":"skip","issue_number":0,"reason":"no viable targets"}'
  export STUB_CURL_OLLAMA_OK=1
  export STUB_GH_ISSUE_LIST_OUTPUT='[]'
  export STUB_GH_PR_LIST_OUTPUT='[]'
}

teardown() {
  rm -rf "$TEST_TMPDIR"
}

@test "skip path: Stage 1 runs, emits skip plan, Stages 2 and 3 do not run" {
  run "$BATS_TEST_DIRNAME/../tick.sh"
  [ "$status" -eq 0 ]

  tick_dir="$CHITIN_SINK_ROOT/ticks/$HERMES_TICK_DATE/$HERMES_TICK_TS"
  [ -f "$tick_dir/plan.json" ]
  [ -f "$tick_dir/queue.json" ]
  [ ! -f "$tick_dir/diff.patch" ]
  [ ! -f "$tick_dir/act-log.txt" ]

  # Stage 1 invoked exactly once
  grep -c '^hermes chat -Q --model glm-5.1:cloud' "$STUB_LOG" | grep -qx 1

  # Stage 2 (qwen) never invoked
  ! grep -q 'qwen3-coder' "$STUB_LOG"

  # Stage 3 (ACT) never invoked
  ! grep -q 'Stage 3 (ACT)' "$STUB_LOG"
}

@test "external path: Stage 1 + Stage 3 run, Stage 2 does not" {
  export STUB_HERMES_PLAN_OUTPUT='{"action":"external","issue_number":10,"reason":"groom","external_action":{"kind":"label","body_or_label":"hermes-autonomous","linked_issue":10}}'

  run "$BATS_TEST_DIRNAME/../tick.sh"
  [ "$status" -eq 0 ]

  tick_dir="$CHITIN_SINK_ROOT/ticks/$HERMES_TICK_DATE/$HERMES_TICK_TS"
  [ -f "$tick_dir/plan.json" ]
  [ -f "$tick_dir/act-log.txt" ]
  [ ! -f "$tick_dir/diff.patch" ]

  grep -q 'Stage 1 (PLAN)' "$STUB_LOG"
  grep -q 'Stage 3 (ACT)'  "$STUB_LOG"
  ! grep -q 'Stage 2 (CODE)' "$STUB_LOG"
  ! grep -q 'qwen3-coder'     "$STUB_LOG"
}

@test "code path + ollama ok: all three stages run; diff.patch written" {
  export STUB_HERMES_PLAN_OUTPUT='{"action":"code","issue_number":10,"reason":"fix ESM import","diff_request":{"files":["apps/cli/src/telemetry/jsonl-tailer.ts"],"intent":"append .js extension"}}'
  # Seed the target file so apply-search-replace.py has real source to
  # edit. Content must contain the SEARCH text below verbatim.
  mkdir -p "$HERMES_TICK_REPO_ROOT/apps/cli/src/telemetry"
  printf '%s\n' 'import { foo } from "./event-parser";' \
    > "$HERMES_TICK_REPO_ROOT/apps/cli/src/telemetry/jsonl-tailer.ts"
  export STUB_HERMES_CODE_OUTPUT='=== FILE: apps/cli/src/telemetry/jsonl-tailer.ts ===
<<<<<<< SEARCH
import { foo } from "./event-parser";
=======
import { foo } from "./event-parser.js";
>>>>>>> REPLACE'
  export STUB_CURL_OLLAMA_OK=1

  run "$BATS_TEST_DIRNAME/../tick.sh"
  [ "$status" -eq 0 ]

  tick_dir="$CHITIN_SINK_ROOT/ticks/$HERMES_TICK_DATE/$HERMES_TICK_TS"
  [ -f "$tick_dir/plan.json" ]
  [ -f "$tick_dir/sr-output.txt" ]
  [ -f "$tick_dir/diff.patch" ]
  [ -f "$tick_dir/act-log.txt" ]
  [ "$(cat "$tick_dir/ollama-probe.txt")" = "ok" ]

  # Diff was generated by difflib from actual file state.
  grep -q '^--- a/apps/cli/src/telemetry/jsonl-tailer.ts' "$tick_dir/diff.patch"
  grep -q '^+import { foo } from "./event-parser.js";' "$tick_dir/diff.patch"

  grep -q 'Stage 1 (PLAN)' "$STUB_LOG"
  grep -q 'Stage 2 (CODE)' "$STUB_LOG"
  grep -q 'Stage 3 (ACT)'  "$STUB_LOG"
  grep -q 'qwen3-coder'    "$STUB_LOG"
}

@test "code path + ollama unreachable: Stage 1 runs; Stages 2 & 3 skipped" {
  export STUB_HERMES_PLAN_OUTPUT='{"action":"code","issue_number":10,"reason":"fix ESM import","diff_request":{"files":["apps/cli/src/telemetry/jsonl-tailer.ts"],"intent":"append .js extension"}}'
  export STUB_CURL_OLLAMA_OK=0

  run "$BATS_TEST_DIRNAME/../tick.sh"
  [ "$status" -eq 0 ]

  tick_dir="$CHITIN_SINK_ROOT/ticks/$HERMES_TICK_DATE/$HERMES_TICK_TS"
  [ -f "$tick_dir/plan.json" ]
  [ ! -f "$tick_dir/diff.patch" ]
  [ ! -f "$tick_dir/act-log.txt" ]
  [ "$(cat "$tick_dir/ollama-probe.txt")" = "unreachable" ]

  ! grep -q 'qwen3-coder' "$STUB_LOG"
  ! grep -q 'Stage 3 (ACT)' "$STUB_LOG"
}

@test "streak: counter increments on each unreachable, resets on reachable" {
  export STUB_HERMES_PLAN_OUTPUT='{"action":"code","issue_number":10,"reason":"fix","diff_request":{"files":["x.ts"],"intent":"fix"}}'
  streak_file="$CHITIN_SINK_ROOT/ollama-unreachable-streak.txt"

  # Run 1 — unreachable
  export STUB_CURL_OLLAMA_OK=0
  export HERMES_TICK_TS="20260422T000000Z"
  run "$BATS_TEST_DIRNAME/../tick.sh"
  [ "$status" -eq 0 ]
  [ "$(cat "$streak_file")" = "1" ]

  # Run 2 — unreachable
  export HERMES_TICK_TS="20260422T001000Z"
  run "$BATS_TEST_DIRNAME/../tick.sh"
  [ "$(cat "$streak_file")" = "2" ]

  # Run 3 — unreachable
  export HERMES_TICK_TS="20260422T002000Z"
  run "$BATS_TEST_DIRNAME/../tick.sh"
  [ "$(cat "$streak_file")" = "3" ]

  # Run 4 — reachable → reset
  export STUB_CURL_OLLAMA_OK=1
  export HERMES_TICK_TS="20260422T003000Z"
  run "$BATS_TEST_DIRNAME/../tick.sh"
  [ "$(cat "$streak_file")" = "0" ]
}

@test "dry-run: external action path — stage 3 invoked with HERMES_TICK_DRY_RUN=1 in env" {
  export STUB_HERMES_PLAN_OUTPUT='{"action":"external","issue_number":10,"reason":"groom","external_action":{"kind":"label","body_or_label":"hermes-autonomous","linked_issue":10}}'

  run "$BATS_TEST_DIRNAME/../tick.sh" --dry-run
  [ "$status" -eq 0 ]

  tick_dir="$CHITIN_SINK_ROOT/ticks/$HERMES_TICK_DATE/$HERMES_TICK_TS"
  [ -f "$tick_dir/act-log.txt" ]
  grep -q 'HERMES_TICK_DRY_RUN=1' "$STUB_LOG"
}

@test "concurrency guard: second tick exits cleanly when lock is held" {
  # Hold the lock in an inherited fd from a subshell that blocks until we
  # let it go. If tick.sh sees the lock busy, it must exit 0 without
  # running any stages.
  ready_file="$TEST_TMPDIR/lock-holder.ready"
  ( flock -x 200; touch "$ready_file"; sleep 5 ) 200>"$HERMES_TICK_LOCK_FILE" &
  lock_holder=$!
  # Wait (up to ~2.5s) for the holder to signal it has the lock.
  for _ in $(seq 1 50); do
    [[ -f "$ready_file" ]] && break
    sleep 0.05
  done
  [[ -f "$ready_file" ]]

  run "$BATS_TEST_DIRNAME/../tick.sh"
  [ "$status" -eq 0 ]

  # No stage 1 invocation, no tick dir contents — the run short-circuited
  # before queue fetch.
  ! grep -q '^hermes chat' "$STUB_LOG"
  tick_dir="$CHITIN_SINK_ROOT/ticks/$HERMES_TICK_DATE/$HERMES_TICK_TS"
  [ ! -f "$tick_dir/plan.json" ]

  # The skip message goes to stderr so cron-tick.log captures it.
  echo "$output" | grep -q 'lock held by another run'

  kill "$lock_holder" 2>/dev/null || true
  wait "$lock_holder" 2>/dev/null || true
}

@test "fence strip: stage 2 SR output wrapped in code fences is parsed successfully" {
  export STUB_HERMES_PLAN_OUTPUT='{"action":"code","issue_number":10,"reason":"fix","diff_request":{"files":["x.ts"],"intent":"append .js"}}'
  mkdir -p "$HERMES_TICK_REPO_ROOT"
  printf '%s\n' 'import { foo } from "./bar";' > "$HERMES_TICK_REPO_ROOT/x.ts"
  # Model wraps its SR output in a fenced block despite prompt rules.
  # The fence lines must be stripped before apply-search-replace.py
  # tries to parse.
  export STUB_HERMES_CODE_OUTPUT='```
=== FILE: x.ts ===
<<<<<<< SEARCH
import { foo } from "./bar";
=======
import { foo } from "./bar.js";
>>>>>>> REPLACE
```'

  run "$BATS_TEST_DIRNAME/../tick.sh"
  [ "$status" -eq 0 ]

  tick_dir="$CHITIN_SINK_ROOT/ticks/$HERMES_TICK_DATE/$HERMES_TICK_TS"
  # Fences gone from sr-output; diff was produced from actual file state.
  ! grep -q '^```' "$tick_dir/sr-output.txt"
  grep -q '^--- a/x.ts' "$tick_dir/diff.patch"
  grep -q '^+import { foo } from "./bar.js";' "$tick_dir/diff.patch"
  grep -q 'stage 2 done' "$tick_dir/tick.log"
}

@test "SR parse failure: no blocks in model output short-circuits before stage 3" {
  export STUB_HERMES_PLAN_OUTPUT='{"action":"code","issue_number":10,"reason":"fix","diff_request":{"files":["x.ts"],"intent":"fix"}}'
  mkdir -p "$HERMES_TICK_REPO_ROOT"
  printf '%s\n' 'import { foo } from "./bar";' > "$HERMES_TICK_REPO_ROOT/x.ts"
  export STUB_HERMES_CODE_OUTPUT='the model just wrote prose — no SEARCH/REPLACE blocks anywhere'

  run "$BATS_TEST_DIRNAME/../tick.sh"
  [ "$status" -eq 0 ]

  tick_dir="$CHITIN_SINK_ROOT/ticks/$HERMES_TICK_DATE/$HERMES_TICK_TS"
  grep -q 'stage 2 search_replace_failed' "$tick_dir/tick.log"
  grep -q 'no SEARCH/REPLACE blocks found' "$tick_dir/sr-apply.err"
  # Stage 3 never ran — no act-log.
  [ ! -f "$tick_dir/act-log.txt" ]
  ! grep -q 'Stage 3 (ACT)' "$STUB_LOG"
}

@test "SR apply failure: SEARCH text not in file short-circuits before stage 3" {
  export STUB_HERMES_PLAN_OUTPUT='{"action":"code","issue_number":10,"reason":"fix","diff_request":{"files":["x.ts"],"intent":"fix"}}'
  mkdir -p "$HERMES_TICK_REPO_ROOT"
  printf '%s\n' 'import { foo } from "./bar";' > "$HERMES_TICK_REPO_ROOT/x.ts"
  # SEARCH block does not appear in x.ts verbatim.
  export STUB_HERMES_CODE_OUTPUT='=== FILE: x.ts ===
<<<<<<< SEARCH
import { ghost } from "./nothing";
=======
import { ghost } from "./nothing.js";
>>>>>>> REPLACE'

  run "$BATS_TEST_DIRNAME/../tick.sh"
  [ "$status" -eq 0 ]

  tick_dir="$CHITIN_SINK_ROOT/ticks/$HERMES_TICK_DATE/$HERMES_TICK_TS"
  grep -q 'stage 2 search_replace_failed' "$tick_dir/tick.log"
  grep -q 'SEARCH not found in file' "$tick_dir/sr-apply.err"
  [ ! -f "$tick_dir/act-log.txt" ]
}

@test "SR off-plan path: block targeting file outside plan.diff_request.files is rejected" {
  export STUB_HERMES_PLAN_OUTPUT='{"action":"code","issue_number":10,"reason":"fix","diff_request":{"files":["x.ts"],"intent":"fix"}}'
  mkdir -p "$HERMES_TICK_REPO_ROOT"
  printf '%s\n' 'stay away' > "$HERMES_TICK_REPO_ROOT/y.ts"
  printf '%s\n' 'x content' > "$HERMES_TICK_REPO_ROOT/x.ts"
  export STUB_HERMES_CODE_OUTPUT='=== FILE: y.ts ===
<<<<<<< SEARCH
stay away
=======
compromised
>>>>>>> REPLACE'

  run "$BATS_TEST_DIRNAME/../tick.sh"
  [ "$status" -eq 0 ]

  tick_dir="$CHITIN_SINK_ROOT/ticks/$HERMES_TICK_DATE/$HERMES_TICK_TS"
  grep -q 'stage 2 search_replace_failed' "$tick_dir/tick.log"
  grep -q 'block targets path outside plan' "$tick_dir/sr-apply.err"
  # The off-plan file on disk is untouched.
  [ "$(cat "$HERMES_TICK_REPO_ROOT/y.ts")" = "stay away" ]
}

@test "retry budget: N stage-2 failures on the same issue apply hermes-gate-blocked label" {
  export STUB_HERMES_PLAN_OUTPUT='{"action":"code","issue_number":42,"reason":"fix","diff_request":{"files":["x.ts"],"intent":"fix"}}'
  mkdir -p "$HERMES_TICK_REPO_ROOT"
  printf '%s\n' 'x content' > "$HERMES_TICK_REPO_ROOT/x.ts"
  # Model always produces unmatched SR, triggering stage 2 failure.
  export STUB_HERMES_CODE_OUTPUT='=== FILE: x.ts ===
<<<<<<< SEARCH
not in file
=======
replacement
>>>>>>> REPLACE'
  # Default budget is 3; take 3 ticks with fresh timestamps.
  for i in 1 2 3; do
    export HERMES_TICK_TS="20260422T00${i}000Z"
    run "$BATS_TEST_DIRNAME/../tick.sh"
    [ "$status" -eq 0 ]
  done

  # After the 3rd failure the issue is re-labeled.
  grep -q 'blockade_applied: #42 relabeled hermes-gate-blocked' \
    "$CHITIN_SINK_ROOT/ticks/$HERMES_TICK_DATE/20260422T003000Z/tick.log"
  grep -q 'gh issue edit 42 --repo chitinhq/chitin --remove-label hermes-autonomous --add-label hermes-gate-blocked' \
    "$STUB_LOG"
  # Counter was reset after blockade so a future tick won't immediately re-fire.
  [ "$(jq -r '."42" // "absent"' "$CHITIN_SINK_ROOT/issue-failure-counts.json")" = "absent" ]
}

@test "retry budget: counter resets when stage 2 succeeds" {
  export STUB_HERMES_PLAN_OUTPUT='{"action":"code","issue_number":43,"reason":"fix","diff_request":{"files":["x.ts"],"intent":"fix"}}'
  mkdir -p "$HERMES_TICK_REPO_ROOT"
  printf '%s\n' 'before' > "$HERMES_TICK_REPO_ROOT/x.ts"

  # Tick 1: stage 2 fails (SEARCH not in file).
  export STUB_HERMES_CODE_OUTPUT='=== FILE: x.ts ===
<<<<<<< SEARCH
missing
=======
replacement
>>>>>>> REPLACE'
  export HERMES_TICK_TS="20260422T000000Z"
  run "$BATS_TEST_DIRNAME/../tick.sh"
  [ "$status" -eq 0 ]
  [ "$(jq -r '."43"' "$CHITIN_SINK_ROOT/issue-failure-counts.json")" = "1" ]

  # Tick 2: stage 2 succeeds. Counter should be cleared.
  export STUB_HERMES_CODE_OUTPUT='=== FILE: x.ts ===
<<<<<<< SEARCH
before
=======
after
>>>>>>> REPLACE'
  export HERMES_TICK_TS="20260422T001000Z"
  run "$BATS_TEST_DIRNAME/../tick.sh"
  [ "$status" -eq 0 ]
  [ "$(jq -r '."43" // "absent"' "$CHITIN_SINK_ROOT/issue-failure-counts.json")" = "absent" ]
}

@test "in-flight worktree: pre-existing chitin-N dir causes code action to skip" {
  export STUB_HERMES_PLAN_OUTPUT='{"action":"code","issue_number":10,"reason":"fix","diff_request":{"files":["x.ts"],"intent":"fix"}}'
  # A worktree already exists for issue #10 — likely from an earlier tick
  # still finishing. Skip rather than duplicate the attempt.
  mkdir -p "$HERMES_TICK_WORKTREE_BASE/chitin-10"

  run "$BATS_TEST_DIRNAME/../tick.sh"
  [ "$status" -eq 0 ]

  tick_dir="$CHITIN_SINK_ROOT/ticks/$HERMES_TICK_DATE/$HERMES_TICK_TS"
  grep -q 'in_flight_local' "$tick_dir/tick.log"
  # Stage 2 never ran.
  [ ! -f "$tick_dir/diff.patch" ]
  ! grep -q 'qwen3-coder' "$STUB_LOG"
}
