#!/usr/bin/env python3
"""Regenerate docs/superpowers/specs/INDEX.md from spec front-matter.

Reads YAML front-matter from every spec under `docs/superpowers/specs/`
and `docs/superpowers/superseded/`, groups by status, and writes a
deterministic INDEX.md.

Determinism: within each status group, rows are sorted by `effective_from`
descending (newest first), with a stable tie-breaker on file path. The
output is byte-identical across re-runs on the same input.

Usage:
    python3 scripts/regen-spec-index.py [--check]

    --check  Exit non-zero if INDEX.md on disk differs from the regenerated
             output. CI uses this to enforce that committed INDEX.md is
             in sync.
"""

from __future__ import annotations

import argparse
import difflib
import sys
from pathlib import Path

try:
    import yaml
except ImportError:
    sys.stderr.write("regen-spec-index: PyYAML is required.\n")
    sys.exit(2)


INDEX_PATH = Path("docs/superpowers/specs/INDEX.md")
ROOTS = (
    Path("docs/superpowers/specs"),
    Path("docs/superpowers/superseded"),
)
EXEMPT_NAMES = {"INDEX.md", "README.md"}

STATUS_ORDER = ("open", "amended", "implemented", "draft", "superseded")
STATUS_HEADERS = {
    "open": "Open",
    "amended": "Amended",
    "implemented": "Implemented",
    "draft": "Draft",
    "superseded": "Superseded",
}


def parse_frontmatter(path: Path) -> dict | None:
    text = path.read_text(encoding="utf-8")
    if not text.startswith("---\n"):
        return None
    end = text.find("\n---", 4)
    if end == -1:
        return None
    try:
        data = yaml.safe_load(text[4:end])
    except yaml.YAMLError:
        return None
    return data if isinstance(data, dict) else None


def extract_title(path: Path) -> str:
    """Best-effort title extraction: first `# ` line after front-matter."""
    text = path.read_text(encoding="utf-8")
    if text.startswith("---\n"):
        end = text.find("\n---", 4)
        if end != -1:
            text = text[end + 4:]
    for line in text.splitlines():
        line = line.strip()
        if line.startswith("# "):
            title = line[2:].strip()
            for prefix in ("Spec: ", "Spec — ", "spec: "):
                if title.startswith(prefix):
                    return title[len(prefix):]
            return title
    return path.stem


def gather() -> list[dict]:
    rows: list[dict] = []
    for root in ROOTS:
        if not root.exists():
            continue
        for p in sorted(root.rglob("*.md")):
            if p.name in EXEMPT_NAMES:
                continue
            fm = parse_frontmatter(p)
            if fm is None:
                continue
            rows.append({
                "path": str(p),
                "title": extract_title(p),
                "status": fm.get("status", "draft"),
                "owner": fm.get("owner") or "—",
                "kanban": fm.get("kanban") or "—",
                "implementation_pr": fm.get("implementation_pr"),
                "superseded_by": fm.get("superseded_by"),
                "effective_from": str(fm.get("effective_from") or ""),
                "effective_to": str(fm.get("effective_to") or ""),
            })
    return rows


def fmt_pr(pr) -> str:
    if pr in (None, ""):
        return "—"
    return f"#{pr}"


def fmt_kanban(k) -> str:
    if not k or k == "—":
        return "—"
    return f"`{k}`"


def render(rows: list[dict]) -> str:
    buckets: dict[str, list[dict]] = {s: [] for s in STATUS_ORDER}
    unknown: list[dict] = []
    for r in rows:
        if r["status"] in buckets:
            buckets[r["status"]].append(r)
        else:
            unknown.append(r)

    for s in buckets:
        buckets[s].sort(
            key=lambda r: (r["effective_from"], r["path"]),
            reverse=True,
        )

    out: list[str] = []
    out.append("# Spec index")
    out.append("")
    out.append(
        "_Auto-generated by `scripts/regen-spec-index.py`. Do not edit by hand._"
    )
    out.append("")
    out.append(
        "Schema and lifecycle defined in "
        "[`docs/superpowers/specs/2026-05-13-spec-lifecycle-metadata.md`]"
        "(2026-05-13-spec-lifecycle-metadata.md) and "
        "[`docs/runbooks/spec-lifecycle.md`](../../runbooks/spec-lifecycle.md)."
    )
    out.append("")

    total = sum(len(b) for b in buckets.values()) + len(unknown)
    out.append(f"**Total specs tracked:** {total}")
    out.append("")

    for status in STATUS_ORDER:
        rows_for_status = buckets[status]
        out.append(f"## {STATUS_HEADERS[status]} ({len(rows_for_status)})")
        out.append("")
        if not rows_for_status:
            out.append("_(none)_")
            out.append("")
            continue

        if status == "superseded":
            out.append("| Date | Title | Path | Superseded by |")
            out.append("|------|-------|------|---------------|")
            for r in rows_for_status:
                sb = r["superseded_by"] or "—"
                out.append(
                    f"| {r['effective_from'] or '—'} "
                    f"| {r['title']} "
                    f"| `{r['path']}` "
                    f"| {sb} |"
                )
        elif status == "implemented":
            out.append("| Date | Title | Path | Owner | Kanban | PR |")
            out.append("|------|-------|------|-------|--------|-----|")
            for r in rows_for_status:
                out.append(
                    f"| {r['effective_from'] or '—'} "
                    f"| {r['title']} "
                    f"| `{r['path']}` "
                    f"| {r['owner']} "
                    f"| {fmt_kanban(r['kanban'])} "
                    f"| {fmt_pr(r['implementation_pr'])} |"
                )
        else:
            out.append("| Date | Title | Path | Owner | Kanban |")
            out.append("|------|-------|------|-------|--------|")
            for r in rows_for_status:
                out.append(
                    f"| {r['effective_from'] or '—'} "
                    f"| {r['title']} "
                    f"| `{r['path']}` "
                    f"| {r['owner']} "
                    f"| {fmt_kanban(r['kanban'])} |"
                )
        out.append("")

    if unknown:
        out.append(f"## Unknown status ({len(unknown)})")
        out.append("")
        out.append("| Path | Reported status |")
        out.append("|------|------------------|")
        for r in unknown:
            out.append(f"| `{r['path']}` | {r['status']} |")
        out.append("")

    return "\n".join(out) + "\n"


def main() -> int:
    p = argparse.ArgumentParser()
    p.add_argument(
        "--check",
        action="store_true",
        help="Exit non-zero if INDEX.md on disk differs from regenerated.",
    )
    args = p.parse_args()

    rows = gather()
    rendered = render(rows)

    if args.check:
        if not INDEX_PATH.exists():
            print(
                f"regen-spec-index --check: {INDEX_PATH} does not exist.\n"
                "Run `python3 scripts/regen-spec-index.py` and commit the result.",
                file=sys.stderr,
            )
            return 1
        current = INDEX_PATH.read_text(encoding="utf-8")
        if current != rendered:
            diff = difflib.unified_diff(
                current.splitlines(keepends=True),
                rendered.splitlines(keepends=True),
                fromfile=f"{INDEX_PATH} (committed)",
                tofile=f"{INDEX_PATH} (regenerated)",
            )
            sys.stderr.write(
                f"regen-spec-index --check: {INDEX_PATH} is out of date.\n"
                "Run `python3 scripts/regen-spec-index.py` and commit.\n\n"
            )
            sys.stderr.writelines(diff)
            return 1
        print(f"regen-spec-index --check: {INDEX_PATH} is up to date "
              f"({len(rows)} specs)")
        return 0

    INDEX_PATH.parent.mkdir(parents=True, exist_ok=True)
    INDEX_PATH.write_text(rendered, encoding="utf-8")
    print(f"regen-spec-index: wrote {INDEX_PATH} ({len(rows)} specs)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
